<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart  custom-link-cart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
        <div>
            <!-- <i class="fa fa-shopping-bag"></i> -->
            <svg xmlns="http://www.w3.org/2000/svg" width="30.531" height="36" viewBox="0 0 30.531 36"><defs><style>.a{fill:none;stroke:#261d2c;stroke-miterlimit:10;}</style></defs><g transform="translate(-307.62 -114.55)"><path class="a" d="M433.12,160.05h6.927v5.833" transform="translate(-106.771 -38.438)"/><path class="a" d="M355.62,125.258v-4.74a5.469,5.469,0,0,1,5.469-5.469h0a5.469,5.469,0,0,1,5.469,5.469v4.74" transform="translate(-40.573)"/><path class="a" d="M383.12,121.613v-1.094a5.469,5.469,0,0,1,5.469-5.469h0a5.469,5.469,0,0,1,5.469,5.469v1.094" transform="translate(-64.062)"/><line class="a" x2="2.917" transform="translate(313.589 125.258)"/><line class="a" x2="2.917" transform="translate(324.526 125.258)"/><line class="a" x2="8.021" transform="translate(315.412 121.613)"/><path class="a" d="M333.276,188.488V160.05h4.375v28.438H308.12V160.05h4.375" transform="translate(0 -38.438)"/></g></svg>
            <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
            <span class="counter qty empty"
                data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() },
                blockLoader: isLoading">
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
                </span>
            </span>
        </div>
        <div>
            <span class="label-cart">MY CART</span>    
            </br>
             <!-- ko if: getCartParam('summary_count') -->
                    <span data-bind="html: getCartParam('subtotal')" class="subtotal-cart"></span>
                    <!-- /ko -->
                    <!-- ko ifnot: getCartParam('summary_count') -->
                        <span class="subtotal-cart">SGD 0.00</span>
                    <!-- /ko -->
                <!-- <span data-bind="html: getCartParam('subtotal')" class="subtotal-cart"></span> -->

        </div>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()):?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else: ?>
        <?php $scriptString = <<<script
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
     /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>
