<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 * 
 */
/** @var Magento\Customer\Block\Account\Customer $block */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>


<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) : ?>
<div class="custom-wishlist">
        <span class="header_account_link_list logout">
            <a class= "header_account_link wishlist-custom" href="<?php echo $this->getUrl("customer/account/logout");?>">
                <svg xmlns="http://www.w3.org/2000/svg" width="16.342" height="18.3" viewBox="0 0 16.342 18.3"><defs><style>.a{fill:#393535;stroke:#393535;stroke-width:0.3px;}</style></defs><g transform="translate(-297.23 -272.505)"><path class="a" d="M306.257,515.062h-1.711a7.174,7.174,0,0,0-7.165,7.165v.034a1.206,1.206,0,0,0,1.2,1.2h13.633a1.206,1.206,0,0,0,1.2-1.2v-.034A7.174,7.174,0,0,0,306.257,515.062Zm6.366,7.2a.406.406,0,0,1-.405.405H298.585a.406.406,0,0,1-.405-.405v-.034a6.373,6.373,0,0,1,6.366-6.366h1.711a6.373,6.373,0,0,1,6.366,6.366Z" transform="translate(0 -232.811)"/><path class="a" d="M394.945,281.315a4.33,4.33,0,1,0-4.33-4.33A4.335,4.335,0,0,0,394.945,281.315Zm0-7.861a3.531,3.531,0,1,1-3.53,3.53A3.535,3.535,0,0,1,394.945,273.455Z" transform="translate(-89.544 0)"/></g></svg>
                </br>
                <?php echo __('Logout')?>
            </a>
        </span>  
    </div>
<?php else: ?>
	
    <li class="link authorization-link customs-auth" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
        <a class="auth-custom" <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>>
            <!-- <i class="far fa-user"></i> -->
            <svg xmlns="http://www.w3.org/2000/svg" width="16.342" height="18.3" viewBox="0 0 16.342 18.3"><defs><style>.a{fill:#393535;stroke:#393535;stroke-width:0.3px;}</style></defs><g transform="translate(-297.23 -272.505)"><path class="a" d="M306.257,515.062h-1.711a7.174,7.174,0,0,0-7.165,7.165v.034a1.206,1.206,0,0,0,1.2,1.2h13.633a1.206,1.206,0,0,0,1.2-1.2v-.034A7.174,7.174,0,0,0,306.257,515.062Zm6.366,7.2a.406.406,0,0,1-.405.405H298.585a.406.406,0,0,1-.405-.405v-.034a6.373,6.373,0,0,1,6.366-6.366h1.711a6.373,6.373,0,0,1,6.366,6.366Z" transform="translate(0 -232.811)"/><path class="a" d="M394.945,281.315a4.33,4.33,0,1,0-4.33-4.33A4.335,4.335,0,0,0,394.945,281.315Zm0-7.861a3.531,3.531,0,1,1-3.53,3.53A3.535,3.535,0,0,1,394.945,273.455Z" transform="translate(-89.544 0)"/></g></svg>
            </br>
            <span>Login/Register</span> </a>
    </li>
<?php endif;?>
